version: 0.2

phases:
  pre_build:
    commands:
      - echo "Executing pre-build steps"
  build:
    commands:
      - echo "Building deployment artifact..."
      - zip -r DeployArtifact backend  # Package the specific folder
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files: DeployArtifact.zip  # Artifact to be used in the next pipeline stage