# .github/workflows/deploy.yml
name: Android Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Decrypt keystore file
      run: openssl enc -aes-256-cbc -d -in android_app/scanalyze-release-key.jks.enc -out android_app/scanalyze-release-key.jks
      env:
        OPENSSL_PASSWORD: ${{ secrets.RELEASE_ENCRYPTED_KEYSTORE_PASSWORD }}

    - name: Writing the github secrets to the local.properties file
      run: echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android_app/local.properties
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android_app/local.properties
            echo "storeFile=${{ secrets.RELEASE_STORE_FILEPATH }}" >> android_app/local.properties
            echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android_app/local.properties

    - name: Build APK
      run: |
        cd android_app
        ./gradlew assembleRelease

    - name: Rename APK
      run: mv android_app/app/build/outputs/apk/release/app-release-unsigned.apk android_app/app/build/outputs/apk/release/scanalyze.apk

    - name: Deploy APK to S3
      run: aws s3 cp ./android_app/app/build/outputs/apk/release/scanalyze.apk s3://${{secrets.AWS_S3_BUCKET}} --region ${{secrets.AWS_REGION}}
      env:
        AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

  
